version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose the development server port
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/node_modules  # Prevents overwriting node_modules in the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensure file changes are detected inside Docker
